version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - yum install sshpass
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      # - chmod 644 ~/.ssh/config
      # - ssh -oStrictHostKeyChecking=no "corp\greg"@35.153.149.177
